version: '3.7'

networks:
  web-app:

services:
  # Container: NginX
  nginx:
    networks:
      - web-app
    container_name: nginx
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    image: nginx:nginx-stable-alpine
    ports:
      - "9100:80"
    volumes:
      - "${PATH_PROJECT_SOURCE}:/var/www/html"
      - "${PATH_NGINX_CONFIGS}:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
      - mysql

  # Container: MySQL
  mysql:
    networks:
      - web-app
    container_name: mysql
    build:
      context: .
      dockerfile: containers/mysql/Dockerfile
    image: mysql:mysql-5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - "${DB_MYSQL_VOLUME}:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "${DB_MYSQL_DATABASE}"
      MYSQL_USER: "${DB_MYSQL_USER}"
      MYSQL_PASSWORD: "${DB_MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_MYSQL_ROOT_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  # Container: PHP
  php:
    networks:
      - web-app
    container_name: php
    build:
      context: .
      dockerfile: containers/php/Dockerfile
    image: php:php-7.4-fpm-alpine
    ports:
      - "9000:9000"
    volumes:
      - "${PATH_PROJECT_SOURCE}:/var/www/html"

  # Container: Composer
  composer:
    networks:
      - web-app
    container_name: composer
    build:
      context: .
      dockerfile: containers/composer/Dockerfile
    image: composer:composer-2.1.5
    #image: composer:2.1.5
    working_dir: /var/www/html
    volumes:
      - "${PATH_PROJECT_SOURCE}:/var/www/html"

  # Container: NPM
  npm:
    networks:
      - web-app
    container_name: npm
    image: node:16-alpine
    working_dir: /var/www/html
    volumes:
        - "${PATH_PROJECT_SOURCE}:/var/www/html"
    entrypoint: ['npm']

  # Container: Artisan
  artisan:
    networks:
      - web-app
    container_name: artisan
    build:
      context: .
      dockerfile: containers/php/Dockerfile
    image: artisan:laravel-5.8
    env_file:
      - ../docker/environments/${APP_ENV}.env
    working_dir: /var/www/html
    volumes:
        - "${PATH_PROJECT_SOURCE}:/var/www/html"
    depends_on:
      - mysql
    entrypoint: ['/var/www/html/artisan']
