version: '3.7'

networks:
  web-app:

services:
  # +----------------------+ #
  # | Container: NginX     | #
  # +----------------------+ #
  nginx:
    networks:
      - web-app
    container_name: nginx
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    image: nginx:nginx-stable-alpine
    ports:
      - "9100:80"
    volumes:
      - "${PATH_PROJECT_SOURCE}:/var/www/html"
      - "${PATH_NGINX_CONFIGS}:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
      - mysql

  # +----------------------+ #
  # | Container: MySQL     | #
  # +----------------------+ #
  mysql:
    networks:
      - web-app
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    build:
      context: .
      dockerfile: containers/mysql/Dockerfile
    image: mysql:mysql-8.0.30
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    env_file:
      - ${PATH_ENV_CONFIGS}/${SYS_ENV}.env
    volumes:
      - "${DB_VOLUME}:/var/lib/mysql"
    environment:
#      MYSQL_DATABASE: "${DB_NAME}"
#      MYSQL_USER: "${DB_USERNAME}"
#      MYSQL_PASSWORD: "${DB_PASSWORD}"
#      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD_ROOT}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  # +----------------------+ #
  # | Container: PHP       | #
  # +----------------------+ #
  php:
    networks:
      - web-app
    container_name: php
    build:
      context: .
      dockerfile: containers/php/Dockerfile
    image: php:php-8.1-fpm-alpine
    ports:
      - "9000:9000"
    volumes:
      - "${PATH_PROJECT_SOURCE}:/var/www/html"

  # +----------------------+ #
  # | Container: Composer  | #
  # +----------------------+ #
  composer:
    networks:
      - web-app
    container_name: composer
    build:
      context: .
      dockerfile: containers/composer/Dockerfile
    image: composer:composer-2.1.5
    working_dir: /var/www/html
    volumes:
      - "${PATH_PROJECT_SOURCE}:/var/www/html"
    entrypoint: ['composer']

  # +----------------------+ #
  # | Container: NPM       | #
  # +----------------------+ #
  npm:
    networks:
      - web-app
    container_name: npm
    image: node:16-alpine
    working_dir: /var/www/html
    volumes:
      - "${PATH_PROJECT_SOURCE}:/var/www/html"
    entrypoint: ['npm']

  # +----------------------+ #
  # | Container: Artisan   | #
  # +----------------------+ #
  artisan:
    networks:
      - web-app
    container_name: artisan
    build:
      context: .
      dockerfile: containers/php/Dockerfile
    image: artisan:laravel-8
    env_file:
      - ${PATH_ENV_CONFIGS}/config.env
      - ${PATH_ENV_CONFIGS}/${SYS_ENV}.env
    working_dir: /var/www/html
    volumes:
      - "${PATH_PROJECT_SOURCE}:/var/www/html"
    depends_on:
      - mysql
    entrypoint: ['/var/www/html/artisan']
