name: Docker Image CI

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_KEY: ${{ secrets.DOCKER_KEY }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_KEY

    - name: Scripts
      run: chmod +x -R ./scripts/*.sh
    # Build Docker Images
    - name: Build the Docker image
      run: ./scripts/build.sh

    - name: Start
      run: ./scripts/up.sh -d

    - name: Composer      
      run: ./scripts/composer.sh install
      
